from django.urls import path
from .views import Store,add_product_page, Add_Category,ProductCreateView,Ajax_Search_Products,ProductDetailTemplateView,sslcommerz_payment,sslcommerz_callback,complete_emi,order_form,payment_success,order_success,ProductCreateView,VendorProductListView,AllProductsView,admin_order_list_view,vendor_order_list_view,ProductUpdateView,ProductDeleteView,order_details_api,submit_review,OrderUpdateView,pending_status_view,received_status_view,processing_status_view,transit_status_view,delivered_status_view,CartListCreateView, CartDeleteView, WishlistListCreateView,CartUpdateView, WishlistDeleteView,order_from_cart,CategoryListCreateView, CategoryDetailView,SubCategoryListCreateView,SubCategoryDetailView,SubcategoriesByCategoryView
urlpatterns = [
    path('store/',Store, name='store'),
    path('dashboard/add-product/', add_product_page, name='add-product-page'),
    path('dashboard/add-category/', Add_Category, name='add-category'),
    path('categories/', CategoryListCreateView.as_view(), name='category-list-create'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(), name='category-detail'),

    # SubCategory endpoints
    path('subcategories/', SubCategoryListCreateView.as_view(), name='subcategory-list-create'),
    path('subcategories/<int:pk>/', SubCategoryDetailView.as_view(), name='subcategory-detail'),
    path('subcategories/by-category/<int:category_id>/', SubcategoriesByCategoryView.as_view(), name='subcategories-by-category'),
    path('add-product/', ProductCreateView.as_view(), name='add-product'),
    path('products/', AllProductsView.as_view(), name='all-product'),
    path('products/details/<int:pk>/', ProductDetailTemplateView.as_view(), name='product-detail-page'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product-update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product-delete'),
    path('ajax/search/', Ajax_Search_Products, name='ajax_search_products'),
    path('order/', order_form, name='order-form'),
    path('order/from-cart/', order_from_cart, name='order-cart'),
    path('payment/<int:order_id>/', sslcommerz_payment, name='sslcommerz-payment'),
    path('payment/callback/', sslcommerz_callback, name='sslcommerz-callback'),
    path('payment/success/', payment_success, name='payment-success'),
    path('order/success/', order_success, name='order-success'),
    path('complete-emi/<int:order_id>/', complete_emi, name='complete-emi'),
    path('vendor/create-product/', ProductCreateView.as_view(), name='vendor-create-product'),
    path('vendor/products/', VendorProductListView.as_view(), name='vendor-products'),
    path('orders/', admin_order_list_view, name='orders'),
    path('orders/pending/',pending_status_view, name='pending'),
    path('orders/received/',received_status_view, name='received'),
    path('orders/transit/',transit_status_view, name='transit'),
    path('orders/processing/',processing_status_view, name='processing'),
    path('orders/delivered/',delivered_status_view, name='delivered'),
    path('orders/<int:pk>/', OrderUpdateView.as_view(), name='order-update'),
    path('vendor/orders/', vendor_order_list_view, name='vendor_order_list'),
    path('orders/details/<int:order_id>/', order_details_api, name='order_details_api'),
    path('review/<int:product_id>/', submit_review, name='submit_review'),
    path("cart/", CartListCreateView.as_view(), name="cart-list-create"),
    path("cart/<int:pk>/", CartDeleteView.as_view(), name="cart-delete"),
    path("cart/update/<int:pk>/", CartUpdateView.as_view(), name="cart-update"),
    path("wishlist/", WishlistListCreateView.as_view(), name="wishlist-list-create"),
    path("wishlist/<int:pk>/", WishlistDeleteView.as_view(), name="wishlist-delete"),
    
    ]
