# Generated by Django 5.1.5 on 2025-07-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_rename_content_message_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
