# Generated by Django 5.1.5 on 2025-07-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
    ]
