# Generated by Django 5.1.5 on 2025-08-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(blank=True, default=15, max_length=255),
            preserve_default=False,
        ),
    ]
