# Generated by Django 5.1.5 on 2025-08-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_vendor_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
