# Generated by Django 5.1.5 on 2025-08-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_vendor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='district',
            field=models.CharField(default=8, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='division',
            field=models.CharField(default=9, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='license_image',
            field=models.ImageField(default=14, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='nid_back',
            field=models.ImageField(default=16, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='nid_front',
            field=models.ImageField(default=875, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='profile_image',
            field=models.ImageField(default=42, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='sub_district',
            field=models.CharField(default=17, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
