# Generated by Django 5.1.5 on 2025-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_vendor_district_vendor_division_vendor_license_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
