# Generated by Django 5.1.5 on 2025-08-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_vendor_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='union',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
