# Generated by Django 5.1.5 on 2025-07-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_order_status_order_category_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='vat',
        ),
    ]
