# Generated by Django 5.1.5 on 2025-07-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_order_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
