# Generated by Django 5.1.5 on 2025-07-10 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_status_order_emi_bank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='emi_bank',
        ),
        migrations.RemoveField(
            model_name='order',
            name='emi_duration',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('processing', 'Processing'), ('transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
