# Generated by Django 5.1.5 on 2025-07-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_is_paid_alter_order_emi_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
