# Generated by Django 5.1.5 on 2025-07-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_cost_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cost_price',
        ),
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
